### ISSUE TITLE
need to set LD_LIBRARY_PATH for default install on Debian 11

### ISSUE THREAD

**Issue by dimpase** [kimwalisch/primecount#45] opened 2021-11-18 14:55 UTC
Not 100% sure why, but I cannot run `primecount` installed with the default procedure into /usr/local/ on Debian 11.
Specifically, I see
```
$ ldd /usr/local/bin/primecount
        linux-vdso.so.1 (0x00007ffc34ff6000)
        libprimecount.so.7 => not found
        libprimesieve.so.9 => not found
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4428ba7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4428a63000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4428a49000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4428884000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4428d9d000)
```

Does one need to set some  cmake options (for buidling shared libraries/exacutables with rpath?) while building in such a case?

(Normally speaking one ought to be able to produce an executable knowing location of each dylib - I know that cmake goes its own strange way there, something to do with https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling - but I don't get details).

**Comment by kimwalisch** [comment] 2021-11-18 16:28
> Does one need to set some cmake options (for buidling shared libraries/exacutables with rpath?) while building in such a case?

If you have built libprimecount yourself then the default installation path is usually ```/usr/local/lib``` which is not part of ```LD_LIBRARY_PATH``` on many OSes. Hence you may need to export some environment variables (ideally in your ```~/.bashrc``` or ```~/.profile```):

```sh
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=/usr/local/include:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=/usr/local/include:$C_INCLUDE_PATH
```

This annoying issue was already present in Linux 10 years ago, I thought this issue had been fixed by most Linux distributions in the meantime but it seems the issue is still present. Unfortunately, I don't think there is anything I can do to directly fix this issue in primecount's ```CMakeLists.txt```. I could however add the above documentation to primecount's README.

Another option to fix this issue is to install to ```/usr``` (which is always in the PATH) instead of ```/usr/local```. This can be done using ```cmake . -DCMAKE_INSTALL_PREFIX=/usr``` (but this is not 100% portable, I think it will not work on macOS). This is also not a good general solution, but if you just want it to work on your PC then it will likely fix the issue.

**Comment by kimwalisch** [comment] 2021-11-18 16:37
Note that this issue will not occur if primecount/libprimecount is installed using the Linux distribution's package manager because then the installation path is ```/usr``` which is always in the path.

**Comment by dimpase** [comment] 2021-11-18 16:42
LD_LIBRARY_PATH is normally empty nowadays, and setting it is non-portable, etc. I ran into this while working on a Python wrapper for primecount on https://github.com/dimpase/primecount - I need to link to libprimecount.so, installed *somewhere*, and cannot just modify the environment the Python extension will run in. IMHO the following is relevant:
https://stackoverflow.com/questions/24598047/why-does-ld-need-rpath-link-when-linking-an-executable-against-a-so-that-needs

**Comment by dimpase** [comment] 2021-11-18 17:15
Here is a small example (I don't know cmake well, so just command line).
Say, we have a dynamic library libadd.so in /usr/local/lib, built (Linux-like only) from 
```C
/*  add.c;   build with 
   gcc -o libadd.so -fPIC -shared add.c
   sudo mv libadd.so /usr/local/lib
*/
int myadd(int a, int b) 
{
        return a+b;
}
```
Now, let's call it from the following
```C
/* addcall.c */
#include <stdio.h>
extern int myadd(int, int);

int main()
{
        printf("\n %d\n", myadd(2,2));
        return 0;
}
```
Build `a.out` without setting rpath, and look at its linkage:
```shell
gcc addcall.c  -ladd
$ ldd a.out 
```
we see that `not found` thing as above:
```
        linux-vdso.so.1 (0x00007ffe9e6ac000)
        libadd.so => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007df5be668000)
        /lib64/ld-linux-x86-64.so.2 (0x00007df5be846000)
```
and `a.out` doesn't run without `LD_LIBRARY_PATH` set.
```
$ ./a.out 
./a.out: error while loading shared libraries: libadd.so: cannot open shared object file: No such file or directory
```
But if I build `a.out` with rpath set, as follows, and look at its linkage:
```shell
gcc addcall.c -Wl,-rpath=/usr/local/lib/ -ladd
ldd a.out
```
then we see all is good:
```
        linux-vdso.so.1 (0x00007fffbcb7e000)
        libadd.so => /usr/local/lib/libadd.so (0x00007fe005610000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe005439000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe00561c000)
```
and indeed `a.out` runs:
```
$ ./a.out 

 4
```

------------------

I'd be very surprised if CMAKE didn't provide you a platform-independent way to do this for the `primecount` executable.
(GNU libtool etc certainly are capable of this - perhaps not on Windows though).

And if fact there is a [CMAKE doc](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling) on rpath,
but it's not too clear to me.

**Comment by kimwalisch** [comment] 2021-11-18 17:16
Based on your feedback I found this link: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling

### Default RPATH settings
> By default if you don't change any RPATH related settings, CMake will
link the executables and shared libraries with full RPATH to all used
libraries in the build tree. **When installing, it will clear the RPATH of
these targets so they are installed with an empty RPATH**. 

@dimpase This seems to explain your issue. Before the installation RPATH is used and everything works. Then during the installation RPATH gets cleared and it stops working out of the box.

### Always full RPATH

> In many cases you will want to make sure that the required libraries are
always found independent from LD_LIBRARY_PATH and the install
location. Then you can use these settings:

```CMake
# use, i.e. don't skip the full RPATH for the build tree
set(CMAKE_SKIP_BUILD_RPATH FALSE)

# when building, don't use the install RPATH already
# (but later on when installing)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)

set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")

# add the automatically determined parts of the RPATH
# which point to directories outside the build tree to the install RPATH
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

# the RPATH to be used when installing, but only if it's not a system directory
list(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
if("${isSystemDir}" STREQUAL "-1")
    set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
endif("${isSystemDir}" STREQUAL "-1")
```

So this could potentially fix your issue and would also generally be an improvement for both primesieve and primecount. But the solution is compilcated so I don't fully understand all its implications yet. Especially if these changes would cause issues for the primesieve/primecount distro packages.

**Comment by dimpase** [comment] 2021-11-18 18:48
I found that adding the following somewhere in the beginning of `CMakeLists.txt`
```
set(CMAKE_SKIP_BUILD_RPATH  FALSE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
```
causes both `primecount` binary and `libprimecount` to have their runpaths not stripped.
I suppose this is the same as running `cmake` as
```shell 
cmake -DCMAKE_SKIP_BUILD_RPATH=FALSE -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
           -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
           -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib"
```
(assuming `CMAKE_INSTALL_PREFIX` env.var. set to appropriate value)

Perhaps something along these lines may be included in the  README

**Comment by kimwalisch** [comment] 2021-11-18 19:46
Thanks for the info. I will study CMake & RPATH more in-depth over the next week and also check how other projects use CMake & RPATH. Based on my current understanding the tricky part is that we want to clear RPATH during installation if the installation path is a system path e.g. /usr/lib (I guess distro package managers require this) and not clear it for all other paths (including /usr/local).

These changes could potentially make it much more convenient for users to install primesieve & primecount from source.

**Comment by dimpase** [comment] 2021-11-19 10:51
Same behaviour on Gentoo, so that's not something Debian-specific.

**Comment by dimpase** [comment] 2021-11-19 11:13
Another Linux way, which works if `ldconfig` is configured to look at `/usr/local/lib*`: after `sudo make install` (the default settings, installing in `/usr/local`), run
```shell
sudo ldconfig
```
This updates `ldconfig's` cache, no need to deal with  `LD_LIBRARY_PATH`.

**Comment by kimwalisch** [comment] 2021-11-19 11:21
I did read up on RPATH and unfortunately it is a minefiled i.e. it works differently on Linux and macOS. Also it may break the build/install when using rarely used/niche linkers and requires extra link options on some operating systems. Here is LLVM's compilcated RPATH handling code: https://github.com/llvm/llvm-project/blob/00ff774fca787af4fecbcab6d7ee5f454127c8a1/llvm/cmake/modules/AddLLVM.cmake#L2132.

From what I have read so far it seems that it is not a good idea to use non default RPATH settings in the ```CMakeLists.txt```. I think the RPATH should be set (if needed) by package maintainers as needed by their distro. The problem with ```/usr/local/lib``` is annoying and I would like to fix it but at this point in time I feel like it is too difficult to do it correctly so that it works reliably in all circumstances. My hope is that in the long run primecount will be packaged for more Linux distributions where there are no library/PATH not found issues.

What I will try though is setting RPATH when packaging primecount for homebrew: https://github.com/kimwalisch/homebrew-primecount/issues/1. This could potentially fix "libprimecount.so" not found if the user did not export DYLD_LIBRARY_PATH.

**Comment by dimpase** [comment] 2021-11-19 12:01
I can equally post here very compelling links on why `LD_LIBRARY_PATH` et al. are dangerous and messy. :-)

One way or another, updating README.md for Linux with the info we gathered here seems to be a good idea.

Note that the instructions are fine, if working on macOS with Homebrew, no need to worry about rpath, apparently
cmake does the right things by default on macOS, while installing in /usr/local.  

I've subscribed myself to kimwalisch/homebrew-primecount#1 - will test it when it's done.

**Comment by kimwalisch** [comment] 2021-11-19 13:23
> One way or another, updating README.md for Linux with the info we gathered here seems to be a good idea.

Yes, I will do that. (Note that this information is already present in [libprimecount.md](https://github.com/kimwalisch/primecount/blob/master/doc/libprimecount.md#c-example) and also in primesieve's [README.md](https://github.com/kimwalisch/primesieve#linking-against-libprimesieve))

I just checked how the meson build system is handling RPATH and /usr/local and it seems like it uses the same default settings than CMake i.e. no RPATH for installed libs. Here are a few comments from meson's author:

* https://github.com/mesonbuild/meson/issues/314

> The established Unix convention is that you should not use rpath for finding public libraries, only for your private ones (like if you have stuff in /usr/lib/foobarlib/libfoobarprivate.so). For libraries that are public but not in the standard location (this includes things like /usr/local/lib) you need to set the LD_LIBRARY_PATH environment variable.

> Setting rpath yourself is very much undefined behaviour. It might work. It might not work. It might stop working at any time for any reason.

> The final product must not contain any traces of the build dir. This is a hard, non-negotiable requirement from Linux distros. If rpath on binaries is not perfectly clean, the package will get autorejected.

So I think primesieve & primecount are following best practices by using CMake's default RPATH settings although I agree that the /usr/local issue on Linux is annoying.

**Comment by dimpase** [comment] 2021-11-19 14:01
> Note that this information is already present in ...

I only see the `LD_LIBRARY_PATH` and friends things there.

I think `ldconfig` solution I mention above is much cleaner (and that's the normal Linux thing, to rely on `ldconfig` if possible).
Libraries in `/usr/local/` are cached by `ldconfig` (certainly on Debian, Gentoo, Ubuntu...). In fact, GNU tools used to build dynamic libraries often either try running `ldconfig` after installation, or at least print a warning asking you to run it.

Imagine the confusion and potential errors you'd get if you removed `/usr/local/lib*` from your manually managed  `LD_LIBRARY_PATH`, and yet the linker continues to pick up libraries from there? 
(As `ldconfig` might have been run semi-automatically by a system update in a meantime).
Or if you have different `LD_LIBRARY_PATH` values in different shell sessions, as you might be having several versions of
`libprimecount` installed, and you mix them up - then you'd be having very difficult to debug errors, and submit confusing bug reports (of non-bugs, in fact).

`LD_LIBRARY_PATH` is useful as a last resort, not as a sustainable day to day mode of operation on Linux. Recommend `ldconfig`, please.

**Comment by kimwalisch** [comment] 2021-11-19 15:15
Thanks for the ldconfig hint, I will read up on it.

**Comment by kimwalisch** [comment] 2021-11-20 08:44
> Recommend ldconfig, please.

Done that.

**Closed by kimwalisch** 2021-11-20 08:44 UTC
